In [1]:
import numpy as np

Program ini adalah program untuk meng-*import* `numpy`

Idenya adalah meng-*import* package `numpy` sebagai `np`

Algoritmanya:
1. Import `numpy`, lalu panggil sebagai `np`

# Nomor 1

## Pendefinisian Fungsi

### Partial Pivoting
Pilih $p \geq k$ terkecil sedemikian sehingga,
$$\left | a_{pk}^{(k)} \right | = \max_{k \leq i \leq n} \left | a_{ik}^{(k)} \right |$$
Kemudian lakukan operasi $E_k \leftrightarrow E_p$

In [2]:
def PartialPivoting(matrix): # Kode untuk partial pivoting
    n = np.shape(matrix)[0] # Banyak baris/persamaan pada matriks
    
    for i in range(n-1):
        below_pivot = abs(matrix[i:,i]) # Mencari lokasi dari kolom yang membuat absolutnya nilai maksimum
        pivot_row = np.argmax(below_pivot)
        if matrix[i,pivot_row+i] == 0: # Jika baris yang akan di pivot nol, maka tidak ada solusi unik
            return "Tidak ada solusi unik"
        else:
            matrix[[pivot_row+i,i]] = matrix[[i,pivot_row+i]] # Pertukaran baris
        
        #Eliminasi gauss
        for j in range(i+1,n):
            m = matrix[j,i]/matrix[i,i] # m = a_ji/a_ii
            matrix[j] = matrix[j]-m*matrix[i]
        print("\n", matrix)
    return matrix

### Scaled Partial Pivoting
Definisikan
$$s_i=\max_{k \leq i \leq n} \left | a_{ij} \right |$$
Pilih $p \geq k$ terkecil sedemikian sehingga
$$\frac{\left | a_{pk}^{(k)} \right |}{s_k}= \max_{k \leq i \leq n} \frac{\left | a_{ik}^{(k)} \right |}{s_i}$$
Kemudian, lakukan operasi $(E_k) \leftrightarrow (E_p)$

In [3]:
def ScaledPartialPivoting(matrix): # Kode untuk Scaled Partial Pivoting
    n = np.shape(matrix)[0] # Ambil ukuran baris dari matriks
    s = np.array([max(abs(matrix[i,:n])) for i in range(n)]) # Menentukan skalar tiap kolom dibandingan masing2 baris yang paling besar
    if 0 in s: # SPL tidak memiliki solusi karena ada baris yang hanya berisi 0
        return "Tidak ada solusi unik"
    for i in range(n-1):
        below_pivot = abs(matrix[i:,i])/s[i:]
        pivot_row = np.argmax(below_pivot)
        if matrix[i,pivot_row+i] == 0: # Jika baris yang akan di pivot nol, maka tidak ada solusi unik
            return "Tidak ada solusi unik"
        else:
            matrix[[pivot_row+i,i]] = matrix[[i,pivot_row+i]] # Pertukaran baris
            s[pivot_row+i],s[i] = s[i],s[pivot_row+i] # Pertukaran baris
        
        # Eliminasi gauss
        for j in range(i+1,n):
            m = matrix[j,i]/matrix[i,i] # m = a_ji/a_ii
            matrix[j] = matrix[j]-m*matrix[i]
            print("\n", matrix)
    return matrix

### Back Substitution
Untuk mencari nilai $x_1,x_2,\ldots,x_n$, lakukan **back substitution**. Dari persamaan terakhir diperoleh

$$x_n=\frac{a_{n,n+1}}{a_{nn}}$$

Substitusi $x_n$ ke-(n-1) diperoleh $x_{n-1}$. Substitusi $x_n$ dan $x_{n-1}$ ke persamaan ke-(n-2) diperoleh $x_{n-2}$ lakukan terus sampai mendapatkan $x_1$.

In [4]:
def BackSubstitution(matrix): # Iterasi pengurangan barisnya
    n = np.shape(matrix)[0] # Ambil ukuran baris dari matriks
    solution = np.zeros(n) # Buat array kosong
    solution[n-1] = matrix[n-1,n]/matrix[n-1, n-1] # Isi array dengan a_(n-1)n/a_(n-1)(n-1)
    for i in range(n-2,-1,-1):
        for j in range(i+1,n): # Banyak persamaan
            matrix[i,n] -= matrix[i,j]*solution[j] # Array untuk menyimpan solusi
        solution[i] = matrix[i,n]/matrix[i,i] # Substitusi balik dimulai
    return solution

### Random Matrix

In [5]:
def augMatrix(n): # Membuat augmented matrix dengan n baris
    augMatrix = [] # Buat list kosong matriks
    for i in range(n-2):
        row = [] # Buat list kosong  untuk baris
        for j in range(n+1):
            row.append(np.random.randint(-99,100)) # Tambahkan angka random ke list baris
        augMatrix.append(row) # Tambahkan list baris ke matriks
    augMatrix.insert(1,firstRow) # Masukan 5 digit pertama NPM sbg baris terakhir
    augMatrix.insert(2,lastRow) # Masukan 5 digit terakhir NPM sbg baris terakhir
    
    return np.array(augMatrix, dtype=float) # Return hasil dengan bentuk array dan type float

Program ini adalah program untuk membuat *augmented matrix* dengan $n$-baris

Idenya adalah membuat matriks dengan baris pertama dan terakhirnya random dengan $\left | a_{ij} \right |<100, a_{ij}\in Z$, baris kedua dengan 5 digit pertama NPM, dan baris ketiga dengan 5 digit terakhir NPM.

Algoritmanya:
1. Definisikan fungsi `augMatrix()` dengan *argument* `n`.
1. Buat list kosong dan simpan dalam variabel `augMatrix`.
1. Buat for loop dengan variabel `i` dan range `(n-2)`.
    1. Buat list kosong dan simpan dalam variabel `row`.
    1. Buat for loop dengan variabel `j` dan range `(n+1)`.
        1. Tambahkan (*append*) hasil random angka dari interval -99 dan 99 dengan module `numpy` pada variabel `row`.
    1. Tambahkan (*append*) variabel `row` pada variabel `augMatrix`.
1. Masukan (*insert*) list `firstRow` pada indeks ke-`1`.
1. Masukan (*insert*) list `lastRow` pada indeks ke-`2`.
1. Kembalikan (*return*) variabel `augMatrix` dengan type `float` dan bentuk array dari module `numpy`.

In [8]:
iter = 1
while True:
    print("Selamat Datang di Program Penyelesaian SPL")
    print("------------------------------------------------------------")
    print("Iterasi",iter)
    
    npm = input("Masukkan NPM anda: ") # Menyimpan input NPM dari user
    firstNpm = list(npm[:5]) # Mengambil 5 digit pertama npm sebagai list string "firstNpm"
    lastNpm = list(npm[-5:]) # Mengambil 5 digit terakhir npm sebagai list string "lastNpm"
    firstRow = [int(item) for item in firstNpm] # Mengubah 5 digit pertama npm menjadi list integer "first_row"
    lastRow = [int(item) for item in lastNpm] # Mengubah 5 digit terakhir npm menjadi list integer "last_row"
    
    augMatrix_pp = np.array([[1,-4,4,7,4],[0,2,-1,0,5],[2,1,1,4,2],[2,-3,2,-5,9]],dtype=float)
    #augMatrix_pp = augMatrix(4) # Simpan augmented matrix random dalam variabel "augMatrix_pp"
    augMatrix_spp = augMatrix_pp.copy() # Copy matriks "augMatrix_pp" sebagai "augMatrix_spp"
    print("Berikut adalah augmented matrix yang terbentuk.\n{0}".format(augMatrix_pp))
    
    print("\n === PARTIAL PIVOTING ===")
    triangularForm_pp = PartialPivoting(augMatrix_pp) # Simpan hasil Partial Pivoting pada "augMatrix_pp"
    print("\n Solusi SPL : \n {0}".format(BackSubstitution(triangularForm_pp))) # Cetak Back Substitution dari hasil Partial Pivoting
    
    print("\n === SCALED PARTIAL PIVOTING ===")
    triangularForm_spp = ScaledPartialPivoting(augMatrix_spp) # Simpan hasil Scaled Partial Pivoting pada "augMatrix_spp"
    print("\n Solusi SPL : \n {0}".format(BackSubstitution(triangularForm_spp))) # Cetak Back Substitution dari hasil Scaled Partial Pivoting
    
    while True: # Proses pemilihan dilakukan secara looping terus untuk menghindari error pada program
        ulang = str(input("\nApakah ingin menjalankan program lagi? ")).lower() # Simpan input yang diinginkan user dalam bentuk string dan paksa menjadi lowercase
        if ulang not in ["y","n"]: # Jika input bukan y/n
            print("Anda salah input, silakan ulang.") # User diminta mengulang
        else: # Jika input y/n
            break # Program keluar dari loop
    
    print("\n===================================\n")
    
    iter+=1 # Tambah 1 pada jumlah iterasi
    
    if ulang == "n": # Jika user memilih n
        break # Program keluar dan berhenti
        
print("~Terima Kasih~") # Cetak pernyataan "Terima Kasih"

Selamat Datang di Program Penyelesaian SPL
------------------------------------------------------------
Iterasi 1
Masukkan NPM anda: 2106725034
Berikut adalah augmented matrix yang terbentuk.
[[ 1. -4.  4.  7.  4.]
 [ 0.  2. -1.  0.  5.]
 [ 2.  1.  1.  4.  2.]
 [ 2. -3.  2. -5.  9.]]

 === PARTIAL PIVOTING ===

 [[ 2.   1.   1.   4.   2. ]
 [ 0.   2.  -1.   0.   5. ]
 [ 0.  -4.5  3.5  5.   3. ]
 [ 0.  -4.   1.  -9.   7. ]]

 [[  2.           1.           1.           4.           2.        ]
 [  0.          -4.5          3.5          5.           3.        ]
 [  0.           0.           0.55555556   2.22222222   6.33333333]
 [  0.           0.          -2.11111111 -13.44444444   4.33333333]]

 [[  2.           1.           1.           4.           2.        ]
 [  0.          -4.5          3.5          5.           3.        ]
 [  0.           0.          -2.11111111 -13.44444444   4.33333333]
 [  0.           0.           0.          -1.31578947   7.47368421]]

 Solusi SPL : 
 [-14.4

Program ini adalah program untuk menyelesaikan sistem persamaan linier (SPL).

Idenya adalah menyelesaikan SPL dengan metode **Partial Pivoting** dan **Scaled Partial Pivoting** dari matriks random yang baris kedua dan ketiganya berasal dari lima digit pertama dan terakhir NPM.

Algoritmanya:
1. Inisiasi nilai iterasi pada variabel `iter` dengan nilai `1`.
1. Buat `While` loop untuk mengulang program secara terus-menerus.
    1. Cetak "Selamat Datang" pada *user* dan informasi banyaknya iterasi.
    1. Simpan input NPM dari *user* dalam sebuah variabel `npm`.
    1. Simpan 5 digit pertama dari NPM yang diubah dalam bentuk list string dalam variabel `firstNpm`.
    1. Simpan 5 digit terakhir dari NPM yang diubah dalam bentuk list string dalam variabel `lastNpm`.
    1. Paksa setiap item dalam list string `firstNpm` menjadi sebuah integer, lalu simpan ke dalam variabel `firstRow`.
    1. Paksa setiap item dalam list string `lastNpm` menjadi sebuah integer, lalu simpan ke dalam variabel `lastRow`.
    1. Simpan hasil panggilan dari fungsi `augMatrix()` yang sudah dibuat dengan baris `4` dalam sebuah variabel `augMatrix_pp`.
    1. Duplikat/*copy* variabel `augMatrix_pp` dalam variabel `augMatrix_spp`.
    1. Cetak hasil *augmented matrix* kepada *user*.
    1. Cetak informasi program **Partial Pivoting**
    1. Simpan hasil `PartialPivoting()` pada variabel `augMatrix_pp` dalam variabel `triangularForm_pp`.
    1. Cetak solusi program dari hasil `BackSubstitution()` pada variabel `triangularForm_pp`.
    1. Cetak informasi program **Scaled Partial Pivoting**
    1. Simpan hasil `ScaledPartialPivoting()` pada variabel `augMatrix_spp` dalam variabel `triangularForm_spp`.
    1. Cetak solusi program dari hasil `BackSubstitution()` pada variabel `triangularForm_spp`.
    1. Buat *loop* untuk *input* permintaan 'menjalankan program lagi' atau 'tidak'. Jika inputnya tidak sesuai, *user* akan diminta input ulang hingga inputnya sesuai. Jika sesuai, maka program akan keluar dari *loop*
    1. Cetak pemisah antar program.
    1. Tambah `1` pada variabel `iter`.
    1. Jika *input user* adalah tidak (`N`/`n`), program akan keluar dari `loop`.
1. Cetak pernyataan "terima kasih" kepada *user*

# Nomor 2

## Pendefinisian Fungsi

Untuk mengurangi banyak operasi pada penyelesaian SPL dengan matriks, faktorisasi matriks seringkali dilakukan. Ada bermacam-macam faktorisasi matriks, namun yang paling umum digunakan adalah faktorisasi LU. Pada faktorisasi LU, matriks A dinyatakan sebagai perkalian antara matriks segitiga bawah L dan matriks segitiga atas U. Atau
$$A=LU$$
Faktorisasi LU dapat dilakukan dengan menggunakan eliminasi Gauss. Jika eliminasi Gauss dapat dilakukan pada sistem Ax = b tanpa melakukan pertukaran baris, maka $A=LU$, dimana $m_{ji}=\frac{a_{ji}^{(i)}}{a_{ii}^{(i)}}$,

$L=\begin{bmatrix}
    1 & 0 & \cdots  & 0 \\
    m_{21} & 1 & \cdots  & 0 \\
    \vdots & \vdots & \ddots & \vdots \\
    m_{n1} & m_{n2} & \cdots  & 1
\end{bmatrix}$

$U=\begin{bmatrix}
    a_{11}^{(1)} & a_{12}^{(1)} & \cdots  & a_{1n}^{(1)} \\
    0 & a_{22}^{(2)} & \cdots  & a_{2n}^{(2)} \\
    \vdots & \vdots & \ddots & \vdots \\
    0 & 0 & \cdots  & a_{nn}^{(n)}
\end{bmatrix}$

In [7]:
def LUFactorization(matrix):
    n = np.shape(matrix)[0] # Mengambil ukuran baris dari matriks
    L = np.identity(n) # Mendefinisikan L sebagai matriks identitas n x n
    
    # Operasi Baris Elementer
    for i in range(n):
        for j in range(i+1, n):
            m = matrix[j,i]/matrix[i,i]
            L[j,i] = round(m) # Set elemen L_ji sebagai hasil rounding m = a_ji/a_ii
            matrix[j] = np.round(matrix[j]-m*matrix[i]) # Set elemen a_j sebagai hasil rounding a_j-m*a_i
    return (L, matrix)

In [8]:
matrix = np.array(eval(input('Masukan matriks A Anda:\n'))) # Untuk menyimpan input matriks yang akan dioperasikan dalam bentuk array

for i in range(10): # Looping hingga 10
    print("========================================\n")
    
    print("Faktorisasi LU matriks A",i) # Cetak faktorisasi LU matriks A ke-i
    L = np.round(LUFactorization(matrix)[0]) # Mengambil L pada LUFactorization
    print("Matriks L\n{0}".format(L)) # Cetak L
    U = np.round(LUFactorization(matrix)[1]) # Mengambil matrix pada LUFactorization
    print("Matriks U\n{0}".format(U)) # Cetak matrix
    
    matrix = L+U # Jumlahkan matriks L dan U
    print(f'Matriks A {i+1}\n{matrix}') # Cetak hasil faktorisasi LU matriks A ke-(i+1)

print("\n***********************")
print(f'Diperoleh matriks A{i+1}:\n{matrix}') # Cetak hasil perolehan matriks

Masukan matriks A Anda:
[[7,3,6],[1,5,2],[6,2,7]]

Faktorisasi LU matriks A 0
Matriks L
[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 1.]]
Matriks U
[[7 3 6]
 [0 5 1]
 [0 0 2]]
Matriks A 1
[[8. 3. 6.]
 [0. 6. 1.]
 [1. 0. 3.]]

Faktorisasi LU matriks A 1
Matriks L
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriks U
[[8. 3. 6.]
 [0. 6. 1.]
 [0. 0. 2.]]
Matriks A 2
[[9. 3. 6.]
 [0. 7. 1.]
 [0. 0. 3.]]

Faktorisasi LU matriks A 2
Matriks L
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriks U
[[9. 3. 6.]
 [0. 7. 1.]
 [0. 0. 3.]]
Matriks A 3
[[10.  3.  6.]
 [ 0.  8.  1.]
 [ 0.  0.  4.]]

Faktorisasi LU matriks A 3
Matriks L
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriks U
[[10.  3.  6.]
 [ 0.  8.  1.]
 [ 0.  0.  4.]]
Matriks A 4
[[11.  3.  6.]
 [ 0.  9.  1.]
 [ 0.  0.  5.]]

Faktorisasi LU matriks A 4
Matriks L
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriks U
[[11.  3.  6.]
 [ 0.  9.  1.]
 [ 0.  0.  5.]]
Matriks A 5
[[12.  3.  6.]
 [ 0. 10.  1.]
 [ 0.  0.  6.]]

Faktorisasi LU matriks A 5
Matriks L
[[1. 0. 0.]
 [0. 1. 0

Program ini adalah program untuk memeroleh nilai A10 dimana $A_n=L_{n-1}+U_{n-1}$.

Idenya adalah melakukan iterasi faktorisasi dan penjumlahan LU dari suatu matriks dimana matriks segitiga bawah (L) dan matriks segitiga atas (U) hingga diperoleh A10.

Algoritmanya:
1. Simpan evaluasi input matriks dari *user* ke dalam variabel `matrix` dalam bentuk array dengan module `numpy`.
1. Buat iterasi for loop pada variabel `i` dengan range `10`.
    1. Cetak pemisah antar iterasi.
    1. Cetak informasi faktorisasi LU pada matriks A iterasi ke-`i`
    1. Simpan rounding dari hasil `LUFactorization()` variabel `matrix` pada indeks ke-`0` dalam variabel `L`.
    1. Cetak matriks dari variabel `L`.
    1. Simpan rounding dari hasil `LUFactorization()` variabel `matrix` pada indeks ke-`1` dalam variabel `U`.
    1. Cetak matriks dari variabel `U`.
    1. Simpan hasil penjumlahan matriks `L` dan `U` pada variabel `matrix`.
    1. Cetak variabel `matrix` dengan informasi matriks A ke-(`i+1`).
1. Cetak pemisah antara hasil dan program.
1. Cetak variabel `matrix` sebagai hasil perolehan operasi.